### ISSUE TITLE
Reassessment every time it is opened

### ISSUE THREAD

**Issue by orcunhanay** [aws/porting-assistant-dotnet-ui#757]
I am successfully assessing two projects. When I turn my computer back on the next day, I want to assess another project. And as you can see in the image, it is assessing previous projects over and over again. I can't get out of this loop.

I installed previous versions via the link below, let's see if there is the same problem in 1.9.1.
https://s3.us-west-2.amazonaws.com/aws.portingassistant.dotnet.download/v1.9.1/windows/Porting-Assistant-DotNet-1.9.1.exe

![Screenshot 2023-02-10 181834](https://user-images.githubusercontent.com/13981015/218760116-33d0ed02-4c7d-4047-8674-27650b8c705e.png)

**Comment by huawenm** [comment]
Thank you for using the Porting Assistant! We have cut a ticket and tried to investigate the issue, but unfortunately we cannot reproduce the issue on 1.9.2. just wondering would you like to share some logs with us or have an online debugging session with us over a call ?  We are happy to help over the call or email. You could reach out us on aws-porting-assistant-support@amazon.com

**Comment by orcunhanay** [comment]
Hi, I sent a few details and logs/dumps containing mail.

**Comment by saikiranakula-amzn** [comment]
As per the conversation, we did see multiple temporary reducer cache files which might be written by many processes. Cleaning up these  file and clearing config caches in the Porting Asssistant .NET folder helped to resolved the white screen issues
